import type Database from 'better-sqlite3';
import { TAXONOMY } from '../../shared/taxonomy';
import { ArchiveRepository } from './repository';
import type { ConditionGrade, ItemInput } from '../../shared/types';

/**
 * Extra descriptive detail for the example records, keyed by type slug. The
 * museum's document gives one example per material type; these fill out the
 * remaining catalogue fields so the item profile screen has realistic content
 * to display on a fresh install.
 */
const DETAILS: Record<
  string,
  {
    dateText: string;
    year: number | null;
    periodEn: string;
    periodAr: string;
    language: string;
    condition: ConditionGrade;
    dimensions: string;
    materialEn: string;
    materialAr: string;
    creatorEn: string;
    creatorAr: string;
    originEn: string;
    originAr: string;
  }
> = {
  'official-documents': {
    dateText: '12 March 1954',
    year: 1954,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'good',
    dimensions: '33 × 21 cm',
    materialEn: 'Paper, ink, official seal',
    materialAr: 'ورق، حبر، ختم رسمي',
    creatorEn: 'Ministry of Culture',
    creatorAr: 'وزارة الثقافة',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  correspondence: {
    dateText: '8 June 1961',
    year: 1961,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'fair',
    dimensions: '29 × 20 cm',
    materialEn: 'Paper, ink',
    materialAr: 'ورق، حبر',
    creatorEn: 'Directorate of the Egyptian Museum',
    creatorAr: 'إدارة المتحف المصري',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  registers: {
    dateText: '1935 – 1947',
    year: 1935,
    periodEn: 'Kingdom of Egypt',
    periodAr: 'المملكة المصرية',
    language: 'Arabic',
    condition: 'fair',
    dimensions: '40 × 28 cm, 214 pages',
    materialEn: 'Bound paper ledger, leather spine',
    materialAr: 'دفتر ورقي مجلد، كعب جلدي',
    creatorEn: 'Civil Registry Office',
    creatorAr: 'مكتب السجل المدني',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  maps: {
    dateText: 'circa 1902',
    year: 1902,
    periodEn: 'Khedivate of Egypt',
    periodAr: 'الخديوية المصرية',
    language: 'Arabic, French',
    condition: 'good',
    dimensions: '70 × 100 cm',
    materialEn: 'Lithograph on paper, linen backing',
    materialAr: 'طباعة حجرية على ورق مبطن بالكتان',
    creatorEn: 'Survey Department of Egypt',
    creatorAr: 'مصلحة المساحة المصرية',
    originEn: 'Luxor, Egypt',
    originAr: 'الأقصر، مصر',
  },
  manuscripts: {
    dateText: '11th century AH / 17th century AD',
    year: 1650,
    periodEn: 'Ottoman Period',
    periodAr: 'العصر العثماني',
    language: 'Arabic',
    condition: 'fair',
    dimensions: '24 × 17 cm, 312 folios',
    materialEn: 'Ink and gold leaf on laid paper, leather binding',
    materialAr: 'حبر وماء الذهب على ورق، تجليد جلدي',
    creatorEn: 'Unknown scribe',
    creatorAr: 'ناسخ غير معروف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  newspapers: {
    dateText: '23 July 1952',
    year: 1952,
    periodEn: 'Revolution of 1952',
    periodAr: 'ثورة 1952',
    language: 'Arabic',
    condition: 'poor',
    dimensions: '58 × 40 cm, 12 pages',
    materialEn: 'Newsprint',
    materialAr: 'ورق صحف',
    creatorEn: 'Al-Ahram Establishment',
    creatorAr: 'مؤسسة الأهرام',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  magazines: {
    dateText: 'Issue 47, October 1965',
    year: 1965,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'good',
    dimensions: '28 × 21 cm, 64 pages',
    materialEn: 'Printed paper, colour cover',
    materialAr: 'ورق مطبوع، غلاف ملون',
    creatorEn: 'General Egyptian Book Organization',
    creatorAr: 'الهيئة المصرية العامة للكتاب',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  books: {
    dateText: '1920',
    year: 1920,
    periodEn: 'British Protectorate',
    periodAr: 'الحماية البريطانية',
    language: 'Arabic',
    condition: 'good',
    dimensions: '25 × 18 cm, 480 pages',
    materialEn: 'Printed paper, cloth binding',
    materialAr: 'ورق مطبوع، تجليد قماشي',
    creatorEn: 'Bulaq Press',
    creatorAr: 'مطبعة بولاق',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  reports: {
    dateText: 'Fiscal year 1978',
    year: 1978,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'excellent',
    dimensions: '30 × 21 cm, 96 pages',
    materialEn: 'Printed paper, spiral binding',
    materialAr: 'ورق مطبوع، تجليد حلزوني',
    creatorEn: 'Egyptian Antiquities Organization',
    creatorAr: 'هيئة الآثار المصرية',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  contracts: {
    dateText: '4 February 1969',
    year: 1969,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic, English',
    condition: 'good',
    dimensions: '33 × 21 cm, 8 pages',
    materialEn: 'Paper, ink, revenue stamps',
    materialAr: 'ورق، حبر، طوابع دمغة',
    creatorEn: 'Ministry of Culture, Legal Affairs',
    creatorAr: 'وزارة الثقافة، الشؤون القانونية',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  photographs: {
    dateText: '15 January 1971',
    year: 1971,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: '—',
    condition: 'good',
    dimensions: '20 × 25 cm',
    materialEn: 'Gelatin silver print',
    materialAr: 'طبعة فضية جيلاتينية',
    creatorEn: 'State Information Service photographer',
    creatorAr: 'مصور الهيئة العامة للاستعلامات',
    originEn: 'Aswan, Egypt',
    originAr: 'أسوان، مصر',
  },
  films: {
    dateText: '1963',
    year: 1963,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'fair',
    dimensions: '35 mm, 3 reels, 42 minutes',
    materialEn: 'Acetate film stock',
    materialAr: 'فيلم أسيتات',
    creatorEn: 'Egyptian General Cinema Organization',
    creatorAr: 'المؤسسة المصرية العامة للسينما',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  slides: {
    dateText: '1982 – 1985',
    year: 1982,
    periodEn: 'Modern',
    periodAr: 'العصر الحديث',
    language: 'Arabic, English',
    condition: 'good',
    dimensions: '35 mm, 120 slides',
    materialEn: 'Colour transparency film, plastic mounts',
    materialAr: 'فيلم شفاف ملون، إطارات بلاستيكية',
    creatorEn: 'Faculty of Archaeology, Cairo University',
    creatorAr: 'كلية الآثار، جامعة القاهرة',
    originEn: 'Giza, Egypt',
    originAr: 'الجيزة، مصر',
  },
  negatives: {
    dateText: 'circa 1930',
    year: 1930,
    periodEn: 'Kingdom of Egypt',
    periodAr: 'المملكة المصرية',
    language: '—',
    condition: 'poor',
    dimensions: '9 × 12 cm glass plates, 24 pieces',
    materialEn: 'Glass plate negatives',
    materialAr: 'نيجاتيف على ألواح زجاجية',
    creatorEn: 'Unknown studio',
    creatorAr: 'استوديو غير معروف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  microfilm: {
    dateText: 'Filmed 1974, originals 1876 – 1950',
    year: 1974,
    periodEn: 'Modern',
    periodAr: 'العصر الحديث',
    language: 'Arabic',
    condition: 'good',
    dimensions: '16 mm, 8 reels',
    materialEn: 'Silver halide microfilm',
    materialAr: 'ميكروفيلم هاليد الفضة',
    creatorEn: 'National Library and Archives of Egypt',
    creatorAr: 'دار الكتب والوثائق القومية',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'audio-recordings': {
    dateText: '26 July 1956',
    year: 1956,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'fair',
    dimensions: '1 reel, 38 minutes',
    materialEn: 'Magnetic reel-to-reel tape',
    materialAr: 'شريط مغناطيسي بكرة',
    creatorEn: 'Egyptian Radio',
    creatorAr: 'الإذاعة المصرية',
    originEn: 'Alexandria, Egypt',
    originAr: 'الإسكندرية، مصر',
  },
  'audio-tapes': {
    dateText: '1988',
    year: 1988,
    periodEn: 'Modern',
    periodAr: 'العصر الحديث',
    language: 'Arabic',
    condition: 'fair',
    dimensions: 'C-90 cassette, 87 minutes',
    materialEn: 'Compact cassette, ferric tape',
    materialAr: 'كاسيت مضغوط، شريط حديدي',
    creatorEn: 'Archive Department oral history programme',
    creatorAr: 'برنامج التاريخ الشفوي بقسم الأرشيف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'phonograph-discs': {
    dateText: 'circa 1928',
    year: 1928,
    periodEn: 'Kingdom of Egypt',
    periodAr: 'المملكة المصرية',
    language: 'Arabic',
    condition: 'poor',
    dimensions: '78 rpm, 30 cm',
    materialEn: 'Shellac disc',
    materialAr: 'أسطوانة شيلاك',
    creatorEn: 'Baidaphon Records',
    creatorAr: 'شركة بيضافون',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'video-recordings': {
    dateText: '6 October 1995',
    year: 1995,
    periodEn: 'Modern',
    periodAr: 'العصر الحديث',
    language: 'Arabic',
    condition: 'good',
    dimensions: 'Betacam SP, 55 minutes',
    materialEn: 'Magnetic video tape',
    materialAr: 'شريط فيديو مغناطيسي',
    creatorEn: 'Egyptian Television',
    creatorAr: 'التلفزيون المصري',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'video-tapes': {
    dateText: '1983',
    year: 1983,
    periodEn: 'Modern',
    periodAr: 'العصر الحديث',
    language: 'Arabic',
    condition: 'fair',
    dimensions: 'VHS E-180, 120 minutes',
    materialEn: 'VHS cassette',
    materialAr: 'شريط VHS',
    creatorEn: 'Egyptian Television, Channel One',
    creatorAr: 'التلفزيون المصري، القناة الأولى',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'digital-video': {
    dateText: '19 November 2019',
    year: 2019,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: 'Arabic, English',
    condition: 'excellent',
    dimensions: 'MP4, 1920×1080, 1.4 GB, 68 minutes',
    materialEn: 'Born-digital video file',
    materialAr: 'ملف فيديو رقمي المنشأ',
    creatorEn: 'Egyptian Museum education programme',
    creatorAr: 'برنامج التوعية بالمتحف المصري',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  email: {
    dateText: '3 May 2021',
    year: 2021,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: 'Arabic, English',
    condition: 'excellent',
    dimensions: 'EML, 42 KB, 2 attachments',
    materialEn: 'Born-digital message',
    materialAr: 'رسالة رقمية المنشأ',
    creatorEn: 'Office of the Museum Director',
    creatorAr: 'مكتب مدير المتحف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  databases: {
    dateText: 'Snapshot of 31 December 2023',
    year: 2023,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: 'Arabic',
    condition: 'excellent',
    dimensions: 'SQL dump, 310 MB, 14 tables',
    materialEn: 'Relational database export',
    materialAr: 'تصدير قاعدة بيانات علائقية',
    creatorEn: 'Human Resources Department',
    creatorAr: 'إدارة الموارد البشرية',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'digital-files': {
    dateText: '30 June 2022',
    year: 2022,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: 'Arabic',
    condition: 'excellent',
    dimensions: 'PDF/A-2b, 18 MB, 144 pages',
    materialEn: 'Born-digital document',
    materialAr: 'مستند رقمي المنشأ',
    creatorEn: 'Archive Department',
    creatorAr: 'قسم الأرشيف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  websites: {
    dateText: 'Captured 14 September 2020',
    year: 2020,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: 'Arabic, English',
    condition: 'good',
    dimensions: 'WARC, 2.1 GB, 3,480 URLs',
    materialEn: 'Web archive capture',
    materialAr: 'نسخة أرشيفية لموقع إلكتروني',
    creatorEn: 'Digital Preservation Unit',
    creatorAr: 'وحدة الحفظ الرقمي',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'digital-images': {
    dateText: 'Scanned 2018 – 2020',
    year: 2018,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: '—',
    condition: 'excellent',
    dimensions: 'TIFF, 600 dpi, 2,140 files, 96 GB',
    materialEn: 'Digital surrogate scans',
    materialAr: 'نسخ رقمية ممسوحة ضوئياً',
    creatorEn: 'Digitisation Laboratory',
    creatorAr: 'معمل الرقمنة',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'digital-recordings': {
    dateText: '12 April 2017',
    year: 2017,
    periodEn: 'Contemporary',
    periodAr: 'العصر المعاصر',
    language: 'Arabic',
    condition: 'excellent',
    dimensions: 'MP3, 320 kbps, 74 minutes',
    materialEn: 'Born-digital audio file',
    materialAr: 'ملف صوتي رقمي المنشأ',
    creatorEn: 'Archive Department oral history programme',
    creatorAr: 'برنامج التاريخ الشفوي بقسم الأرشيف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'engineering-drawings': {
    dateText: '1897',
    year: 1897,
    periodEn: 'Khedivate of Egypt',
    periodAr: 'الخديوية المصرية',
    language: 'French, Arabic',
    condition: 'fair',
    dimensions: '90 × 120 cm, 6 sheets',
    materialEn: 'Ink and wash on tracing linen',
    materialAr: 'حبر وألوان مائية على كتان شفاف',
    creatorEn: 'Marcel Dourgnon, architect',
    creatorAr: 'مارسيل دورنيون، معماري',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  paintings: {
    dateText: 'circa 1911',
    year: 1911,
    periodEn: 'Khedivate of Egypt',
    periodAr: 'الخديوية المصرية',
    language: '—',
    condition: 'good',
    dimensions: '85 × 120 cm, framed',
    materialEn: 'Oil on canvas, gilt wooden frame',
    materialAr: 'زيت على قماش، إطار خشبي مذهب',
    creatorEn: 'Unattributed',
    creatorAr: 'غير منسوبة',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'seals-stamps': {
    dateText: 'circa 1890',
    year: 1890,
    periodEn: 'Khedivate of Egypt',
    periodAr: 'الخديوية المصرية',
    language: 'Arabic, Ottoman Turkish',
    condition: 'good',
    dimensions: '4.5 cm diameter',
    materialEn: 'Engraved brass with wooden handle',
    materialAr: 'نحاس محفور بمقبض خشبي',
    creatorEn: 'Government bureau workshop',
    creatorAr: 'ورشة الديوان الحكومي',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'coins-medals': {
    dateText: '1922',
    year: 1922,
    periodEn: 'Kingdom of Egypt',
    periodAr: 'المملكة المصرية',
    language: 'Arabic',
    condition: 'excellent',
    dimensions: '3.8 cm diameter, 28 g',
    materialEn: 'Struck silver',
    materialAr: 'فضة مسكوكة',
    creatorEn: 'Egyptian Mint',
    creatorAr: 'دار سك العملة المصرية',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  posters: {
    dateText: '1974',
    year: 1974,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: 'Arabic',
    condition: 'fair',
    dimensions: '70 × 50 cm',
    materialEn: 'Colour offset lithograph on paper',
    materialAr: 'طباعة أوفست ملونة على ورق',
    creatorEn: 'Ministry of Culture, Publicity Section',
    creatorAr: 'وزارة الثقافة، قسم الدعاية',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  artifacts: {
    dateText: 'circa 1500 BC',
    year: -1500,
    periodEn: 'New Kingdom, 18th Dynasty',
    periodAr: 'الدولة الحديثة، الأسرة الثامنة عشرة',
    language: '—',
    condition: 'fair',
    dimensions: 'Height 24 cm, rim 14 cm',
    materialEn: 'Fired Nile silt pottery',
    materialAr: 'فخار من طمي النيل محروق',
    creatorEn: 'Unknown potter',
    creatorAr: 'فخراني غير معروف',
    originEn: 'Thebes, Egypt',
    originAr: 'طيبة، مصر',
  },
  models: {
    dateText: '1965',
    year: 1965,
    periodEn: 'Republican Era',
    periodAr: 'العصر الجمهوري',
    language: '—',
    condition: 'good',
    dimensions: '120 × 80 × 45 cm, scale 1:200',
    materialEn: 'Painted plaster and wood',
    materialAr: 'جبس ملون وخشب',
    creatorEn: 'Museum model workshop',
    creatorAr: 'ورشة المجسمات بالمتحف',
    originEn: 'Cairo, Egypt',
    originAr: 'القاهرة، مصر',
  },
  'historical-tools': {
    dateText: 'circa 1940',
    year: 1940,
    periodEn: 'Kingdom of Egypt',
    periodAr: 'المملكة المصرية',
    language: 'Arabic keyboard',
    condition: 'fair',
    dimensions: '32 × 38 × 20 cm, 11 kg',
    materialEn: 'Enamelled steel, rubber, glass keys',
    materialAr: 'صلب مطلي، مطاط، مفاتيح زجاجية',
    creatorEn: 'Olympia Werke AG',
    creatorAr: 'شركة أوليمبيا',
    originEn: 'Germany, used in Cairo',
    originAr: 'ألمانيا، استُخدمت في القاهرة',
  },
};


/**
 * Previous numbers for a few of the example records, so the field is visible
 * on a fresh install. Most records legitimately have none.
 */
const PREVIOUS_NUMBERS: Record<string, { value: string; note: string }[]> = {
  manuscripts: [
    { value: '١٢٤/ب', note: 'Old manuscripts register, 1932' },
    { value: 'MS-0044', note: 'Assigned during the 1968 recataloguing' },
    { value: '77-A', note: 'Conservation department card index' },
  ],
  'official-documents': [{ value: 'D-1954-233', note: 'Ministry file series' }],
  photographs: [
    { value: 'PH/71/015', note: 'Photographic unit log' },
    { value: '4412', note: 'Previous registrar, undated' },
  ],
  artifacts: [{ value: 'JE 38392', note: 'Journal d\'Entrée' }],
};

const FALLBACK = {
  dateText: 'Undated',
  year: null as number | null,
  periodEn: 'Unspecified',
  periodAr: 'غير محدد',
  language: '—',
  condition: 'good' as ConditionGrade,
  dimensions: '—',
  materialEn: '—',
  materialAr: '—',
  creatorEn: 'Unknown',
  creatorAr: 'غير معروف',
  originEn: 'Egypt',
  originAr: 'مصر',
};

/**
 * Populate one example record per material type, taken from the examples in
 * the museum's classification document. Runs once, on a brand-new database
 * only, so it can never overwrite real catalogue work.
 */
export function seedSampleItems(db: Database.Database): void {
  const repo = new ArchiveRepository(db);

  if (repo.getSetting('samples_seeded') === '1') return;

  const existing = (db.prepare('SELECT COUNT(*) AS n FROM items').get() as { n: number }).n;
  if (existing > 0) {
    repo.setSetting('samples_seeded', '1');
    return;
  }

  const typeIdBySlug = new Map<string, number>(
    (db.prepare('SELECT id, slug FROM material_types').all() as { id: number; slug: string }[]).map(
      (r) => [r.slug, r.id],
    ),
  );

  db.transaction(() => {
    for (const category of TAXONOMY) {
      for (const type of category.types) {
        const typeId = typeIdBySlug.get(type.slug);
        if (!typeId) continue;

        const d = DETAILS[type.slug] ?? FALLBACK;

        const input: ItemInput = {
          typeId,
          accessionNo: '',
          previousNumbers: PREVIOUS_NUMBERS[type.slug] ?? [],
          titleEn: type.exampleEn,
          titleAr: type.exampleAr,
          descriptionEn: `${type.exampleEn}. Catalogued under ${type.nameEn} within ${category.nameEn}. This is an example record supplied with the system; replace it with the department's own catalogue data.`,
          descriptionAr: `${type.exampleAr}. مُفهرس ضمن ${type.nameAr} في فئة ${category.nameAr}. هذا سجل نموذجي مرفق مع النظام، ويمكن استبداله ببيانات القسم الفعلية.`,
          creatorEn: d.creatorEn,
          creatorAr: d.creatorAr,
          originEn: d.originEn,
          originAr: d.originAr,
          dateText: d.dateText,
          year: d.year,
          periodEn: d.periodEn,
          periodAr: d.periodAr,
          language: d.language,
          condition: d.condition,
          dimensions: d.dimensions,
          materialEn: d.materialEn,
          materialAr: d.materialAr,
          quantity: 1,
          locationEn: `Store ${category.slug.slice(0, 3).toUpperCase()}, shelf ${type.slug.slice(0, 3).toUpperCase()}`,
          locationAr: `مخزن ${category.nameAr}، رف ${type.nameAr}`,
          acquisitionEn: 'Institutional transfer',
          acquisitionAr: 'نقل مؤسسي',
          acquisitionDate: '',
          notesEn: 'Example record generated from the Archive Department classification document.',
          notesAr: 'سجل نموذجي مُولَّد من وثيقة تصنيف قسم الأرشيف.',
        };

        repo.createItem(input);
      }
    }

    repo.setSetting('samples_seeded', '1');
  })();
}
